name: Website Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secret 
        run: echo "My secret is = ${{ secrets.MY_SECRET }}"

  reusable:
    needs: lint 
    uses: ./.github/workflows/reusable.yml
    with:
      arg1: "value one"
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
