name: reusable workflow
on: 
  workflow_call:
    inputs:
      arg1:
        description: arg number 1, required
        required: true
        type: string
      arg2:
        description: arg number 2, optional
        required: false
        type: string
        default: Value2

    secrets:
      MY_SECRET:

    outputs:
      result:
        description: result of the reusable workflow 
        value: ${{ jobs.job1.outputs.job_result}}

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VALUE: "123qwe"
    outputs:
      job_result: ${{ steps.set-result.outputs.step_result }}
    steps:
      - name: Do the job
        run: echo "Doing ..."
      - name: Use arg1
        run: echo "ARG1 = ${{ inputs.arg1 }}"
      - name: Use arg2
        run: echo "ARG2 = ${{ inputs.arg2 }}"
      - name: Check secret
        run: echo "My secret is = ${{secrets.MY_SECRET}}"
      - name: Set result
        id: set-result
        run: echo "step_result=$VALUE" >> $GITHUB_OUTPUT
